FROM ultisnips

RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ADD doc/minimal_vimrc.vim /root/.vimrc

RUN vim -c 'PlugInstall | qa'
